export default{
    formStyle:{
        marginLeft:"415px",
        height:"400px",
        border:"2px solid silver",
        width:"481px"
    },
    labelStyle:{
        fontFamily:"monospace",
        fontSize:"21px",
        marginLeft:"48px",
        marginTop:"10px"
    },
    inputStyle:{
        marginLeft:"81px",
        marginTop:"10px"
    },
    buttonStyle:{
        borderRadius:"3px",
        height:"28px",
        fontSize:"18px",
        fontFamily:"monospace",
        display:"block",
        marginTop:"301px",
        marginLeft:"401px"
    },
    textAreaStyle:{
        width:"340px",
        height:"250px",
        marginLeft:"70px",
        marginTop:"30px"
    },
    messageButton:{
        borderRadius:"3px",
        height:"28px",
        fontSize:"18px",
        fontFamily:"monospace",
        display:"block",
        marginTop:"72px",
        marginLeft:"401px"
    }
}